# Generated by Django 2.1.3 on 2018-11-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.TextField(blank=True, verbose_name='Middle Name'),
        ),
    ]
