# Generated by Django 2.1.3 on 2018-11-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Base')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Year')),
            ],
            bases=('api.base',),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(unique=True, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='year_level',
            field=models.PositiveSmallIntegerField(verbose_name='Year Level'),
        ),
    ]
