# Generated by Django 2.1.3 on 2018-11-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181121_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Base')),
                ('name', models.TextField(unique=True, verbose_name='Name')),
                ('year_level', models.PositiveSmallIntegerField(verbose_name='Year Level')),
            ],
            bases=('api.base',),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(null=True, unique=True, verbose_name='Name'),
        ),
    ]
