# Generated by Django 2.1.3 on 2018-11-28 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181128_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(verbose_name='Status')),
                ('quarter', models.PositiveSmallIntegerField(verbose_name='Quarter')),
                ('year_level', models.PositiveSmallIntegerField(verbose_name='Year Level')),
                ('school_year', models.PositiveSmallIntegerField(verbose_name='School Year')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
