# Generated by Django 2.1.3 on 2018-11-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181124_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(unique=True, verbose_name='Name'),
        ),
    ]
