# Generated by Django 2.1.3 on 2018-11-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181128_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('school_year', models.TextField(verbose_name='School Year')),
                ('advisor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Teacher')),
                ('batch_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('school_year', models.TextField(verbose_name='School Year')),
                ('advisor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Teacher')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('school_year', models.TextField(verbose_name='School Year')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='Schedule')),
                ('instructor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Teacher')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('school_year', models.TextField(verbose_name='School Year')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.PossibleTeacherPosition')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
