# Generated by Django 2.1.3 on 2018-11-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181128_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectoffering',
            old_name='instructor',
            new_name='teacher',
        ),
    ]
