# Generated by Django 2.1.3 on 2018-11-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181125_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmonthlyrequireddays',
            unique_together={('month', 'school_year')},
        ),
    ]
