from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api.views import *


urlpatterns = format_suffix_patterns([
    path('user/', UsersView.as_view(), name='users'),
    path('user/<int:pk>', UserView.as_view(), name='user'),
    path('user/student/', CreateStudentView.as_view(), name='create_student'),
    path('user/student/<int:pk>/', StudentView.as_view(), name='student'),
    path('user/student/status/',
         CreateStudentStatusView.as_view(),
         name='create_student_status'),
    path('user/student/status/<int:pk>/',
         StudentStatusView.as_view(),
         name='student_status'),
    path('user/student/monthly-attendance/',
         CreateStudentMonthlyAttendanceView.as_view(),
         name='create_student_monthly_attendance'),
    path('user/student/monthly-attendance/<int:pk>/',
         StudentMonthlyAttendanceView.as_view(),
         name='student_monthly_attendance'),
    path('user/student/section/',
         CreateStudentSectionView.as_view(),
         name='create_student_section'),
    path('user/student/section/<int:pk>/',
         StudentSectionView.as_view(),
         name='student_section'),
    path('user/student/rating/',
         CreateStudentRatingView.as_view(),
         name='create_student_rating'),
    path('user/student/rating/<int:pk>/',
         StudentRatingView.as_view(),
         name='student_rating'),
    path('user/student/batch/',
         CreateStudentBatchView.as_view(),
         name='create_student_batch'),
    path('user/student/batch/<int:pk>/',
         StudentBatchView.as_view(),
         name='student_batch'),
    path('student-character-rating-criteria/',
         CreateStudentCharacterRatingCriteriaView.as_view(),
         name='create_student_character_rating_criteria'),
    path('student-character-rating-criteria/<int:pk>/',
         StudentCharacterRatingCriteriaView.as_view(),
         name='student_character_rating_criteria'),
    path('student-monthly-required-days/',
         CreateStudentMonthlyRequiredDaysView.as_view(),
         name='create_student_monthly_required_days'),
    path('student-monthly-required-days/<int:pk>/',
         StudentMonthlyRequiredDaysView.as_view(),
         name='student_monthly_required_days'),
    path('section/', CreateSectionView.as_view(), name='create_section'),
    path('section/<int:pk>/', SectionView.as_view(), name='section'),
    path('batch/', CreateBatchView.as_view(), name='create_batch'),
    path('batch/<int:pk>/', BatchView.as_view(), name='batch'),
    path('subject/', CreateSubjectView.as_view(), name='create_subject'),
    path('subject/<int:pk>/', SubjectView.as_view(), name='subject'),
    path('user/teacher/', CreateTeacherView.as_view(), name='create_teacher'),
    path('user/teacher/<int:pk>/', TeacherView.as_view(), name='teacher'),
    path('possible-teacher-position/',
         CreatePossibleTeacherPositionView.as_view(),
         name='create_possible_teacher_position'),
    path('possible-teacher-position/<int:pk>/',
         PossibleTeacherPositionView.as_view(),
         name='possible_teacher_position'),
    path('user/teacher/position/',
         CreateTeacherPositionView.as_view(),
         name='create_teacher_position'),
    path('user/teacher/position/<int:pk>/',
         TeacherPositionView.as_view(),
         name='teacher_position'),
    path('section/advisor/',
         CreateSectionAdvisorView.as_view(),
         name='create_section_advisor'),
    path('section/advisor/<int:pk>',
         SectionAdvisorView.as_view(),
         name='section_advisor'),
    path('batch/advisor/',
         CreateBatchAdvisorView.as_view(),
         name='create_batch_advisor'),
    path('batch/advisor/<int:pk>/',
         BatchAdvisorView.as_view(),
         name='batch_advisor'),
    path('subject/offering/',
         CreateSubjectOfferingView.as_view(),
         name='create_subject_offering'),
    path('subject/offering/<int:pk>',
         SubjectOfferingView.as_view(),
         name='subject_offering'),
    path('user/admin/', CreateAdminView.as_view(), name='create_admin'),
    path('user/admin/<int:pk>/', AdminView.as_view(), name='admin'),
])